name: Analyze Vowel Frequency
on: 
  push:
    branches:
      - main  # or any other branch you're using

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/georges034302/vowel-frequency-analyzer:latest .
          docker push ghcr.io/georges034302/vowel-frequency-analyzer:latest

      - name: Pull and run Vowel Frequency Analyzer Docker image
        run: |
          docker pull ghcr.io/georges034302/vowel-frequency-analyzer:latest
          docker run --rm -v $PWD:/github/workspace ghcr.io/georges034302/vowel-frequency-analyzer:latest /github/workspace/data.txt
