name: Analyze Vowels Frequency
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and run Vowel Frequency Analyzer Docker image
        run: |
          docker pull ghcr.io/georges034302/vowel-frequency-analyzer:latest
          docker run --rm ghcr.io/georges034302/vowel-frequency-analyzer:latest data.txt
