name: 'Vowel Frequency Analyzer'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Build and run the Docker container
      - name: Build and Run Docker Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/vowel-frequency-analyzer:latest .
          docker run --rm ghcr.io/${{ github.actor }}/vowel-frequency-analyzer:latest /app/data.txt
